# Generated by Django 5.2.6 on 2025-10-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
